### 1. Создать тираж
POST http://127.0.0.1:8000/draws

### 2.1 Купить билет
POST http://127.0.0.1:8000/tickets
Content-Type: application/json

{
  "draw_id": 1,
  "numbers": [3,7,12,25,31]
}

### 2.2 Купить ещё билет
POST http://127.0.0.1:8000/tickets
Content-Type: application/json

{
  "draw_id": 1,
  "numbers": [1,2,11,22,30]
}

### 2.3 И ещё один
POST http://127.0.0.1:8000/tickets
Content-Type: application/json

{
  "draw_id": 1,
  "numbers": [4,6,12,17,22]
}


### 3. Купить билет (неправильный — дубликаты)
POST http://127.0.0.1:8000/tickets
Content-Type: application/json

{
  "draw_id": 1,
  "numbers": [3,7,12,25,31]
}

### 4. Завершить тираж
POST http://127.0.0.1:8000/draws/1/close

### 5. Получить результаты
GET http://127.0.0.1:8000/draws/1/results
